include_guard(GLOBAL)

set(TEMPOLINK_JUCE_CLIENT_SOURCES
  include/tempolink/juce/MainComponent.h
  include/tempolink/juce/app/ClientAppCallbackFactory.h
  include/tempolink/juce/app/ClientAppPresenter.h
  include/tempolink/juce/app/ControllerCompositionFactory.h
  include/tempolink/juce/app/auth/AuthController.h
  include/tempolink/juce/app/content/ContentController.h
  include/tempolink/juce/app/LobbyBindings.h
  include/tempolink/juce/app/lobby/LobbyDataController.h
  include/tempolink/juce/app/navigation/ScreenMode.h
  include/tempolink/juce/app/navigation/ScreenNavigator.h
  include/tempolink/juce/app/navigation/coordinators/RoomCommandUiCoordinator.h
  include/tempolink/juce/app/ParticipantRosterBuilder.h
  include/tempolink/juce/app/RoomCatalog.h
  include/tempolink/juce/app/RoomCommandController.h
  include/tempolink/juce/app/session/SessionLifecycleController.h
  include/tempolink/juce/app/session/SessionPresenceController.h
  include/tempolink/juce/app/SessionBindings.h
  include/tempolink/juce/app/SessionModelSupport.h
  include/tempolink/juce/bridge/AudioFilePlayer.h
  include/tempolink/juce/bridge/AudioRecorder.h
  include/tempolink/juce/bridge/AudioSessionService.h
  include/tempolink/juce/bridge/SessionMediaBridgePort.h
  include/tempolink/juce/bridge/UdpAudioBridgePort.h
  include/tempolink/juce/config/ClientEnvConfig.h
  include/tempolink/juce/constants/ApiPaths.h
  include/tempolink/juce/constants/AuthConstants.h
  include/tempolink/juce/constants/AudioSettingsConstants.h
  include/tempolink/juce/constants/ClientText.h
  include/tempolink/juce/logging/AppLogger.h
  include/tempolink/juce/model/RoomSummary.h
  include/tempolink/juce/network/auth/AuthApiClient.h
  include/tempolink/juce/network/http/common/DocumentContentService.h
  include/tempolink/juce/network/ice/IceConfigClient.h
  include/tempolink/juce/network/ice/IceConfigJsonMapper.h
  include/tempolink/juce/network/ice/IceConfigTypes.h
  include/tempolink/juce/network/http/common/HttpTransport.h
  include/tempolink/juce/network/http/common/JsonParse.h
  include/tempolink/juce/network/http/news/NewsApiClient.h
  include/tempolink/juce/network/auth/OAuthCallbackServer.h
  include/tempolink/juce/network/http/room/RoomApiClient.h
  include/tempolink/juce/network/http/room/RoomApiJsonMapper.h
  include/tempolink/juce/network/http/room/RoomApiPayloadBuilder.h
  include/tempolink/juce/network/http/room/RoomApiTypes.h
  include/tempolink/juce/network/signaling/SignalingClient.h
  include/tempolink/juce/network/signaling/SignalingEventParser.h
  include/tempolink/juce/network/transport/ISocketStreamChannel.h
  include/tempolink/juce/network/transport/PlainSocketStream.h
  include/tempolink/juce/network/transport/TlsSocketStream.h
  include/tempolink/juce/network/transport/PlainWebSocketTransport.h
  include/tempolink/juce/network/transport/TlsWebSocketTransport.h
  include/tempolink/juce/network/transport/SocketStream.h
  include/tempolink/juce/network/transport/WebSocketFrameCodec.h
  include/tempolink/juce/network/transport/WebSocketHandshake.h
  include/tempolink/juce/network/http/user/UsersApiClient.h
  include/tempolink/juce/network/http/user/ProfileApiClient.h
  include/tempolink/juce/style/UiStyle.h
  include/tempolink/juce/style/TempoLinkLookAndFeel.h
  include/tempolink/juce/ui/screens/LobbyView.h
  include/tempolink/juce/ui/screens/LoginView.h
  include/tempolink/juce/ui/screens/ManualView.h
  include/tempolink/juce/ui/screens/MyRoomsView.h
  include/tempolink/juce/ui/screens/NewsView.h
  include/tempolink/juce/ui/components/ParticipantStripComponent.h
  include/tempolink/juce/ui/components/ChatPanel.h
  include/tempolink/juce/ui/screens/ProfileView.h
  include/tempolink/juce/ui/screens/QnaView.h
  include/tempolink/juce/ui/screens/RoomEntrySettingsView.h
  include/tempolink/juce/ui/components/RoomCardComponent.h
  include/tempolink/juce/ui/screens/SessionView.h
  include/tempolink/juce/ui/screens/SettingsView.h
  include/tempolink/juce/ui/models/UiModels.h
  include/tempolink/juce/ui/screens/UsersView.h
  include/tempolink/juce/ui/common/ConnectionBadge.h
  include/tempolink/juce/ui/common/MetricLabel.h
  include/tempolink/juce/ui/common/LevelMeterComponent.h
  include/tempolink/juce/ui/common/PanelCard.h
  include/tempolink/juce/ui/session/MainOutPanel.h
  include/tempolink/juce/ui/session/MyInputPanel.h
  include/tempolink/juce/ui/session/TopStatusBar.h
  src/AppMain.cpp
  src/MainComponent.cpp
  src/app/ClientAppCallbackFactory.cpp
  src/app/ClientAppPresenter.cpp
  src/app/ControllerCompositionFactory.cpp
  src/app/ClientAppPresenter.LoginBindings.cpp
  src/app/ClientAppPresenter.LobbyBindings.cpp
  src/app/ClientAppPresenter.SessionBindings.cpp
  src/app/ClientAppPresenter.UtilityBindings.cpp
  src/app/auth/AuthController.cpp
  src/app/content/ContentController.cpp
  src/app/LobbyBindings.cpp
  src/app/lobby/LobbyDataController.cpp
  src/app/navigation/ScreenNavigator.cpp
  src/app/navigation/coordinators/AuthCoordinator.cpp
  src/app/navigation/coordinators/LobbyCoordinator.cpp
  src/app/navigation/coordinators/RoomCommandUiCoordinator.cpp
  src/app/navigation/coordinators/SessionCoordinator.cpp
  src/app/ParticipantRosterBuilder.cpp
  src/app/RoomCatalog.cpp
  src/app/RoomCommandController.cpp
  src/app/session/SessionLifecycleController.cpp
  src/app/session/SessionPresenceController.cpp
  src/app/SessionBindings.cpp
  src/app/SessionModelSupport.cpp
  src/config/ClientEnvConfig.cpp
  src/style/ThemeManager.cpp
  src/style/TempoLinkLookAndFeel.cpp
  src/bridge/AudioFilePlayer.cpp
  src/bridge/AudioRecorder.cpp
  src/bridge/AudioSessionService.cpp
  src/bridge/SessionMediaBridgePort.cpp
  src/bridge/UdpAudioBridgePort.cpp
  src/logging/AppLogger.cpp
  src/async/AsyncTaskRunner.cpp
  src/network/auth/AuthApiClient.cpp
  src/network/http/common/DocumentContentService.cpp
  src/network/ice/IceConfigClient.cpp
  src/network/ice/IceConfigJsonMapper.cpp
  src/network/http/common/HttpTransport.cpp
  src/network/http/common/JsonParse.cpp
  src/network/http/news/NewsApiClient.cpp
  src/network/auth/OAuthCallbackServer.cpp
  src/network/http/room/RoomApiClient.cpp
  src/network/http/room/RoomApiJsonMapper.cpp
  src/network/http/room/RoomApiPayloadBuilder.cpp
  src/network/signaling/SignalingClient.cpp
  src/network/signaling/SignalingEventParser.cpp
  src/network/transport/PlainSocketStream.cpp
  src/network/transport/TlsSocketStream.cpp
  src/network/transport/PlainWebSocketTransport.cpp
  src/network/transport/TlsWebSocketTransport.cpp
  src/network/transport/SocketStream.cpp
  src/network/transport/WebSocketFrameCodec.cpp
  src/network/transport/WebSocketHandshake.cpp
  src/network/transport/JuceWebSocketTransport.cpp
  src/network/http/user/UsersApiClient.cpp
  src/network/http/user/ProfileApiClient.cpp
  src/ui/screens/LobbyView.cpp
  src/ui/screens/LoginView.cpp
  src/ui/screens/ManualView.cpp
  src/ui/screens/MyRoomsView.cpp
  src/ui/screens/NewsView.cpp
  src/ui/components/ParticipantStripComponent.cpp
  src/ui/components/ChatPanel.cpp
  src/ui/screens/ProfileView.cpp
  src/ui/screens/QnaView.cpp
  src/ui/screens/RoomEntrySettingsView.cpp
  src/ui/components/RoomCardComponent.cpp
  src/ui/screens/SessionView.cpp
  src/ui/screens/SettingsView.cpp
  src/ui/screens/UsersView.cpp
  src/ui/common/ConnectionBadge.cpp
  src/ui/common/MetricLabel.cpp
  src/ui/common/LevelMeterComponent.cpp
  src/ui/common/PanelCard.cpp
  src/ui/session/MainOutPanel.cpp
  src/ui/session/MyInputPanel.cpp
  src/ui/session/TopStatusBar.cpp
)
